---
title: "OpenWeatherMap api wrapper for R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("tmp/settings.R")
```

## Installation

```{r installation, eval=FALSE}
require("devtools")

# stable
install_github("crazycapivara/owmr")

# bleeding edge
install_github("crazycapivara/owmr", ref = "develop")
```

## Status

Beta

## Usage

```{r usage, echo=TRUE, eval=TRUE}
library(owmr)

# pass api key
api_key_ = "your-api-key"
owmr_settings(api_key = api_key)

# get current weather by city name
get_current("London", units = "metric") %>% str()

# ... by city id
(rio <- with(owm_cities, owm_cities[nm == "Rio de Janeiro", ]))
get_current(rio$id, units = "metric") %>%
  unlist %>% .[c("name", "main.temp")]

# ... by coordinates
get_current(lon = rio$lon, lat = rio$lat) %>%
  unlist() %>% .[c("sys.sunrise", "sys.sunset")] %>%
  as.numeric() %>% as.POSIXct(origin = "1970-01-01")

# get weather from stations
find_stations_by_geo_point(lat = 51.31667, lon = 9.5, cnt = 7) %>% 
  .[c("distance", "station.id", "station.name", "last.main.temp")]
  
# get forecast
forecast <- get_forecast("London", units = "metric")

forecast %>% names()

sprintf("%s, %s", forecast$city$name, forecast$city$id)

forecast$cnt

forecast$list %>% nrow()

forecast$list %>% names()

forecast$list[c("dt_txt", "main.temp", "main.temp_max", "wind.speed")] %>% head()

```
