---
title: "owmr - An R Interface to OpenWeatherMap"
output:
  html_document:
    theme: united

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
source("../tmp/settings.R")
```

## Introduction

```{r introduction}
library(owmr)

owm_cities %>% head()

ls("package:owmr") %>% data.frame(obj = .)
```

## Installation

```{r installation, eval=F}
# stable
install.packages("owmr")

# unstable
require("devtools")

devtools::install_github("crazycapivara/owmr/")
```

## Quick start

```{r quick-start}
# Set up API key
owmr_settings(api_key)

# Get latitude and longitude for Rio de Janeiro
rio <- search_city_list("Rio de Janeiro")
rio %>% as.list()

# Fetch current weather data for some cities around Rio de Janeiro
owm_data <- find_cities_by_geo_point(
  lat = rio$lat,
  lon = rio$lon,
  cnt = 9,
  units = "metric")$list %>% tidy_up_()

owm_data %>% names()

# Round temperature values
owm_data <- parse_columns(owm_data, list(temp = round))

# Create popup template to show up on leaflet map
popup_tpl <- paste0(
  "<b>{{name}}</b></br>",
  "{{coord_lon}}, {{coord_lat}}</br>",
  "{{temp}}°C, ",
  "<i>{{weather_description}}</i>"
)

# Test it ...
popup_tpl %$$% owm_data %>% head(2)

# Load leaflet
require("leaflet")

# Create leaflet map and add weather data to it
leaflet(width = "100%") %>%
  addProviderTiles("CartoDB.DarkMatter") %>%
  add_weather(owm_data, icon = owm_data$weather_icon, template = popup_tpl)

## Click on icons to get further information ##

## ... ##
```
